spring.application.name=internship-tracker

# DB (from env)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update

# Base URL used in links
app.base-url=${APP_BASE_URL:https://internship-tracker.tirsansapkota.com}

# Demo note:
# EmailService is disabled via @Profile("!demo"), so mail config not required here.
spring.mail.test-connection=false